# Use root/example as user/password credentials
version: '3.3'

services:
  jenkins_pip:
    build:
      context: src/.
    ports:  # localhost:8080 or localhost -Jenkins will show up
      - 3002:8080
    volumes:
      - jenkinsHome:/var/jenkinsHome
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build: .
    ports:
      - 3001:3001 
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab'
    ports:
      - '80:80'
      #- '443:443'
      #- '22:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
  
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkinsHome:
