# Use root/example as user/password credentials
version: '3.3'

services:
  jenkins:
    build:
      context: src/.
    ports:  # localhost:8080 or localhost -Jenkins will show up
      - 3002:8080
    volumes:
      - jenkinsHome:/var/jenkinsHome
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build: .
    ports:
      - 3001:3001 
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - 80:80
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkinsHome:
