# Use root/example as user/password credentials
version: '3.1'

services:
  my-app: 
   build: 
    context: .
    #image: 558924459154.dkr.ecr.eu-central-1.amazonaws.com/app-pipe:1.2
   ports:
    - 3001:3001
  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  mongo-data:
    driver: local

